### PR TITLE
Update games.js

### PR DESCRIPTION
**Pull request by CharlyKuschel**
{name :  ' Nidhogg 2 ' , Motor :  GAME_MAKER1 , releaseDate : {d :  15 , m :  8 , y :  2017 }, imgId :  ' nidhogg2B ' , yt :  ' ZrAkPDSTLIc ' }

### CODE REVIEW

**Comment by CharlyKuschel** [comment]
nidhogg2b

**Comment by AnnsAnns** [comment]
uhhm, you should maybe include your image in the merge instead of uploading it as a picture xD

**Review by AnnsAnns — CHANGES_REQUESTED** [review]
Add the pictures to a commit

**Comment by letsgamedev** [comment]
Per hand hinzugefügt.

**Pull request closed without merging**
